"resource/ui/hl2r_campaign_browser.res"
{
	"CampaignWindow"
	{
		"ControlName"		"HTML"
		"fieldName"		"CampaignWindow"
		"xpos"		"11"
		"ypos"		"11"
		"wide"		"358"
		"tall"		"430"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"CampaignWindowDivider"
	{
		"ControlName"		"Divider"
		"fieldName"		"CampaignWindowDivider"
		"xpos"		"10"
		"ypos"		"10"
		"wide"		"360"
		"tall"		"432"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"CampaignWindowBackground"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"CampaignWindowBackground"
		"xpos"		"10"
		"ypos"		"10"
		"wide"		"360"
		"tall"		"432"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"scaleImage"		"0"
		"scaleAmount"		"0.000000"
		"tileImage"		"0"
		"tileHorizontally"		"0"
		"tileVertically"		"0"
	}
}
