"resource/ui/hl2r_campaign_list.res"
{
	"listpanel_campaignlistLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"listpanel_campaignlistLabel"
		"xpos"		"10"
		"ypos"		"3"
		"wide"		"256"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_campaign_list_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"listpanel_campaignlist"
	{
		"ControlName"		"SectionedListPanel"
		"fieldName"		"listpanel_campaignlist"
		"xpos"		"10"
		"ypos"		"30"
		"wide"		"465"
		"tall"		"480"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"linespacing"		"40"
		"sectiongap"		"0"
	}
	"SelectedCampaignPanelLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"SelectedCampaignPanelLabel"
		"xpos"		"490"
		"ypos"		"3"
		"wide"		"256"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_editpanel_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"SelectedCampaignPanel"
	{
		"ControlName"		"Panel"
		"fieldName"		"SelectedCampaignPanel"
		"xpos"		"490"
		"ypos"		"29"
		"wide"		"380"
		"tall"		"480"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
	}
	"MountButton"
	{
		"ControlName"		"Button"
		"fieldName"		"MountButton"
		"xpos"		"630"
		"ypos"		"520"
		"wide"		"96"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#hl2r_mountbutton_label"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"mountitem"
		"Default"		"0"
		"button_activation_type" "0"
	}
	"UnmountButton"
	{
		"ControlName"		"Button"
		"fieldName"		"UnmountButton"
		"xpos"		"630"
		"ypos"		"520"
		"wide"		"96"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#hl2r_unmountbutton_label"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"unmountitem"
		"Default"		"0"
		"button_activation_type" "0"
	}
	"CampaignScanButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CampaignScanButton"
		"xpos"		"120"
		"ypos"		"520"
		"wide"		"135"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_scanbutton_label"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"scancampaigns"
		"Default"		"0"
		"button_activation_type" "0"
	}
	"BuildModeDialog"
	{
		"ControlName"		"BuildModeDialog"
		"fieldName"		"BuildModeDialog"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"444"
		"tall"		"410"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#Frame_Untitled"
	}
}
