"resource/ui/hl2r_optionssubvisuals.res"
{
////////////////////////
	// Light Detail
////////////////////////
	"LightDetailBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"LightDetailBox"
		"xpos"		"20"
		"ypos"		"55"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"LightDetailLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"LDLabel"
		"xpos"		"20"
		"ypos"		"30"
		"wide"		"512"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_visualoptions_LD_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"LightDetailDescription"
	{
		"ControlName"		"Label"
		"fieldName"		"LDDescription"
		"xpos"		"170"
		"ypos"		"50"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_visualoptions_LD_description"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Font"		"DefaultSmall"
	}
////////////////////////
	// Projected Muzzleflashes
////////////////////////
	"ProjectedMuzzleflashBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HudHintBox"
		"xpos"		"20"
		"ypos"		"120"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ProjectedMuzzleflashLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PMLabel"
		"xpos"		"20"
		"ypos"		"95"
		"wide"		"512"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_visualoptions_PM_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ProjectedMuzzleflashDescription"
	{
		"ControlName"		"Label"
		"fieldName"		"PMDescription"
		"xpos"		"170"
		"ypos"		"115"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_visualoptions_PM_description"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Font"		"DefaultSmall"
	}
////////////////////////
	// Page Dividers
////////////////////////
	"DividerLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"DLabel"
		"xpos"		"150"
		"ypos"		"165"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_visualoptions_divider_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Divider"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider"
		"xpos"		"10"
		"ypos"		"200"
		"wide"		"385"
		"tall"		"3"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"2"
	}
////////////////////////
	// Quick Info Crosshair
////////////////////////
	"QuickInfoBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"QuickInfoBox"
		"xpos"		"20"
		"ypos"		"235"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"QuickInfoLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"QILabel"
		"xpos"		"20"
		"ypos"		"210"
		"wide"		"512"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_visualoptions_QI_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"QuickInfoDescription"
	{
		"ControlName"		"Label"
		"fieldName"		"QIDescription"
		"xpos"		"170"
		"ypos"		"230"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_visualoptions_QI_description"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Font"		"DefaultSmall"
	}
////////////////////////
	// Minimal Crosshairs
////////////////////////
	"MinCrosshairBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"MinCrosshairBox"
		"xpos"		"20"
		"ypos"		"300"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"MinCrosshairLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"MCLabel"
		"xpos"		"20"
		"ypos"		"275"
		"wide"		"512"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_visualoptions_MC_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"MinCrosshairDescription"
	{
		"ControlName"		"Label"
		"fieldName"		"MCDescription"
		"xpos"		"170"
		"ypos"		"295"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_visualoptions_MC_description"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Font"		"DefaultSmall"
	}
////////////////////////
	// Hud Hints
////////////////////////
	"HudHintBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"HudHintBox"
		"xpos"		"20"
		"ypos"		"365"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"HudHintLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HHLabel"
		"xpos"		"20"
		"ypos"		"340"
		"wide"		"512"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_visualoptions_HH_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"HudHintDescription"
	{
		"ControlName"		"Label"
		"fieldName"		"HHDescription"
		"xpos"		"170"
		"ypos"		"360"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_visualoptions_HH_description"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Font"		"DefaultSmall"
	}
}
