"resource/ui/hl2r_optionssubgame.res"
{
////////////////////////
	// Page Dividers
////////////////////////
	"Divider"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider"
		"xpos"		"10"
		"ypos"		"345"
		"wide"		"385"
		"tall"		"3"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"2"
	}
////////////////////////
	// Episodic Flashlight
////////////////////////
	"EpisodicLightBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"EpisodicLightBox"
		"xpos"		"20"
		"ypos"		"55"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"EpisodicLightLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ELLabel"
		"xpos"		"20"
		"ypos"		"30"
		"wide"		"512"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_EL_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"EpisodicLightDescription"
	{
		"ControlName"		"Label"
		"fieldName"		"ELDescription"
		"xpos"		"170"
		"ypos"		"50"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_EL_description"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Font"		"DefaultSmall"
	}
////////////////////////
	// Zoom Toggle
////////////////////////
	"ZoomToggleBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ZoomToggleBox"
		"xpos"		"20"
		"ypos"		"120"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ZoomToggleLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ZTLabel"
		"xpos"		"20"
		"ypos"		"95"
		"wide"		"512"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_ZT_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ZoomToggleDescription"
	{
		"ControlName"		"Label"
		"fieldName"		"ZTDescription"
		"xpos"		"170"
		"ypos"		"115"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_ZT_description"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Font"		"DefaultSmall"
	}
////////////////////////
	// View Roll
////////////////////////
	"ViewRollSlider"
	{
		"ControlName"		"Slider"
		"fieldName"		"ViewRollSlider"
		"xpos"		"20"
		"ypos"		"200"
		"wide"		"140"
		"tall"		"48"
		"leftText"		" 0      2       4       6      8"
		"rightText"		"10"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"ViewRollLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"VRLabel"
		"xpos"		"20"
		"ypos"		"175"
		"wide"		"512"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_VR_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"ViewRollDescription"
	{
		"ControlName"		"Label"
		"fieldName"		"VRDescription"
		"xpos"		"170"
		"ypos"		"185"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_VR_description"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Font"		"DefaultSmall"
	}
////////////////////////
	// Weapon FOV
////////////////////////
	"WeaponFOVSlider"
	{
		"ControlName"		"Slider"
		"fieldName"		"WeaponFOVSlider"
		"xpos"		"20"
		"ypos"		"265"
		"wide"		"140"
		"tall"		"48"
		"leftText"		"54       63       72       81"
		"rightText"		"90"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"WeaponFOVLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"WFLabel"
		"xpos"		"20"
		"ypos"		"240"
		"wide"		"512"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_WF_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"WeaponFOVDescription"
	{
		"ControlName"		"Label"
		"fieldName"		"WFDescription"
		"xpos"		"170"
		"ypos"		"250"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_WF_description"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Font"		"DefaultSmall"
	}
}
