"resource/ui/hl2r_optionssubchallenges.res"
{
////////////////////////
	// Page Header
////////////////////////
	"HeaderLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HLable"
		"xpos"		"20"
		"ypos"		"15"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_challenges_header_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Page Dividers
////////////////////////
	"Divider"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider"
		"xpos"		"10"
		"ypos"		"60"
		"wide"		"366"
		"tall"		"3"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"2"
	}
////////////////////////
	// Toggle Button
////////////////////////
	"toggleAllButton"
	{
		"ControlName"		"Button"
		"fieldName"		"TAButton"
		"xpos"		"310"
		"ypos"		"640"
		"wide"		"72"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Toggle All"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"command"		"toggleall"
		"Default"		"0"
		"button_activation_type" "0"
	}
////////////////////////	
	// Shorter Sprint
////////////////////////
	"ShorterSprintButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"SSButton"
		"xpos"		"30"
		"ypos"		"80"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_challenges_SS_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"ShorterSprintLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"SSLabel"
		"xpos"		"60"
		"ypos"		"90"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_challenges_SS_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Explosive Headcrabs
////////////////////////
	"ExplosiveCrabsButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ECButton"
		"xpos"		"30"
		"ypos"		"160"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_challenges_EC_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"ExplosiveCrabsLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ECLabel"
		"xpos"		"60"
		"ypos"		"180"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_challenges_EC_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Fear Movement
////////////////////////
	// "FearMovementButton"
	// {
		// "ControlName"		"CheckButton"
		// "fieldName"		"FMButton"
		// "xpos"		"30"
		// "ypos"		"240"
		// "wide"		"200"
		// "tall"		"24"
		// "autoResize"		"0"
		// "pinCorner"		"0"
		// "RoundedCorners"		"15"
		// "pin_corner_to_sibling"		"0"
		// "pin_to_sibling_corner"		"0"
		// "visible"		"1"
		// "enabled"		"1"
		// "tabPosition"		"0"
		// "labelText"		"#hl2r_challenges_FM_title"
		// "textAlignment"		"west"
		// "dulltext"		"0"
		// "brighttext"		"0"
		// "wrap"		"0"
		// "centerwrap"		"0"
		// "textinsetx"		"6"
		// "textinsety"		"0"
		// "auto_wide_tocontents"		"0"
		// "use_proportional_insets"		"0"
		// "Default"		"0"
	// }
	// "FearMovementLabel"
	// {
		// "ControlName"		"Label"
		// "fieldName"		"FMLabel"
		// "xpos"		"60"
		// "ypos"		"250"
		// "wide"		"512"
		// "tall"		"48"
		// "autoResize"		"0"
		// "pinCorner"		"0"
		// "visible"		"1"
		// "enabled"		"1"
		// "tabPosition"		"0"
		// "labelText"		"#hl2r_challenges_FM_text"
		// "textAlignment"		"west"
		// "dulltext"		"0"
		// "brighttext"		"0"
		// "wrap"		"0"
	// }
////////////////////////
	// Less Ammo
////////////////////////
	// "LessAmmoButton"
	// {
		// "ControlName"		"CheckButton"
		// "fieldName"		"LAButton"
		// "xpos"		"30"
		// "ypos"		"320"
		// "wide"		"200"
		// "tall"		"24"
		// "autoResize"		"0"
		// "pinCorner"		"0"
		// "RoundedCorners"		"15"
		// "pin_corner_to_sibling"		"0"
		// "pin_to_sibling_corner"		"0"
		// "visible"		"1"
		// "enabled"		"1"
		// "tabPosition"		"0"
		// "labelText"		"#hl2r_challenges_LA_title"
		// "textAlignment"		"west"
		// "dulltext"		"0"
		// "brighttext"		"0"
		// "wrap"		"0"
		// "centerwrap"		"0"
		// "textinsetx"		"6"
		// "textinsety"		"0"
		// "auto_wide_tocontents"		"0"
		// "use_proportional_insets"		"0"
		// "Default"		"0"
	// }
	// "LessAmmoLabel"
	// {
		// "ControlName"		"Label"
		// "fieldName"		"LALabel"
		// "xpos"		"60"
		// "ypos"		"340"
		// "wide"		"512"
		// "tall"		"48"
		// "autoResize"		"0"
		// "pinCorner"		"0"
		// "visible"		"1"
		// "enabled"		"1"
		// "tabPosition"		"0"
		// "labelText"		"#hl2r_challenges_LA_text"
		// "textAlignment"		"west"
		// "dulltext"		"0"
		// "brighttext"		"0"
		// "wrap"		"0"
	// }
////////////////////////
	// Worst Armor
////////////////////////
//	"WorseArmorButton"
//	{
//		"ControlName"		"CheckButton"
//		"fieldName"		"WAButton"
//		"xpos"		"30"
//		"ypos"		"240"
//		"wide"		"200"
//		"tall"		"24"
//		"autoResize"		"0"
//		"pinCorner"		"0"
//		"RoundedCorners"		"15"
//		"pin_corner_to_sibling"		"0"
//		"pin_to_sibling_corner"		"0"
//		"visible"		"1"
//		"enabled"		"1"
//		"tabPosition"		"0"
//		"labelText"		"#hl2r_challenges_WA_title"
//		"textAlignment"		"west"
//		"dulltext"		"0"
//		"brighttext"		"0"
//		"wrap"		"0"
//		"centerwrap"		"0"
//		"textinsetx"		"6"
//		"textinsety"		"0"
//		"auto_wide_tocontents"		"0"
//		"use_proportional_insets"		"0"
//		"Default"		"0"
//	}
//	"WorseArmorLabel"
//	{
//		"ControlName"		"Label"
//		"fieldName"		"WALabel"
//		"xpos"		"60"
//		"ypos"		"260"
//		"wide"		"512"
//		"tall"		"48"
//		"autoResize"		"0"
//		"pinCorner"		"0"
//		"visible"		"1"
//		"enabled"		"1"
//		"tabPosition"		"0"
//		"labelText"		"#hl2r_challenges_WA_text"
//		"textAlignment"		"west"
//		"dulltext"		"0"
//		"brighttext"		"0"
//		"wrap"		"0"
//	}
////////////////////////
	// Enemy Promotion
////////////////////////
	"EnemyPromotionButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"EPButton"
		"xpos"		"30"
		"ypos"		"240"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_challenges_EP_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"EnemyPromotionLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"EPLabel"
		"xpos"		"60"
		"ypos"		"260"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_challenges_EP_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Random Weapons
////////////////////////
	"RandomWeaponsButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RWButton"
		"xpos"		"30"
		"ypos"		"320"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_challenges_RW_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"RandomWeaponsLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"RWLabel"
		"xpos"		"60"
		"ypos"		"340"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_challenges_RW_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Reduced Assists
////////////////////////
	"ReducedAssistsButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RAButton"
		"xpos"		"30"
		"ypos"		"400"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_challenges_RA_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"ReducedAssistsLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"RALabel"
		"xpos"		"60"
		"ypos"		"420"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_challenges_RA_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Smaller Reserves
////////////////////////
	"SmallerReservesButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"SRButton"
		"xpos"		"30"
		"ypos"		"480"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_challenges_SR_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"SmallerReservesLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"SRLabel"
		"xpos"		"60"
		"ypos"		"500"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_challenges_SR_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
}
