"resource/ui/hl2r_campaign_editor.res"
{
	"CampaignInfoLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"CampaignInfoLabel"
		"xpos"		"15"
		"ypos"		"15"
		"wide"		"256"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_editpanel_campaigninfo_label"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"CampaignIDLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"CampaignIDLabel"
		"xpos"		"115"
		"ypos"		"15"
		"wide"		"256"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"EditBoxDivider"
	{
		"ControlName"		"Divider"
		"fieldName"		"EditBoxDivider"
		"xpos"		"10"
		"ypos"		"40"
		"wide"		"360"
		"tall"		"350"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"EditBoxBackground"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"EditBoxBackground"
		"xpos"		"10"
		"ypos"		"40"
		"wide"		"360"
		"tall"		"350"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"scaleImage"		"0"
		"scaleAmount"		"0.000000"
		"tileImage"		"0"
		"tileHorizontally"		"0"
		"tileVertically"		"0"
	}
	"NameEntryLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"NameEntryLabel"
		"xpos"		"35"
		"ypos"		"60"
		"wide"		"96"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_name_label"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"NameEntry"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"NameEntry"
		"xpos"		"150"
		"ypos"		"60"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"GameSelectBoxLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"GameSelectBoxLabel"
		"xpos"		"35"
		"ypos"		"100"
		"wide"		"115"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gametype_label"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"GameSelectBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"GameSelectBox"
		"xpos"		"150"
		"ypos"		"100"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"2"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ApplyButton"
	{
		"ControlName"		"Button"
		"fieldName"		"ApplyButton"
		"xpos"		"10"
		"ypos"		"400"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#hl2r_editpanel_applybutton_label"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"applychanges"
		"Default"		"0"
		"button_activation_type" "0"
	}
	"MapListPanelTitle"
	{
		"ControlName"		"Label"
		"fieldName"		"MapListPanelTitle"
		"xpos"		"35"
		"ypos"		"160"
		"wide"		"150"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_editpanel_maplist_title_1"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"MapListPanelTitleMapname"
	{
		"ControlName"		"Label"
		"fieldName"		"MapListPanelTitle"
		"xpos"		"150"
		"ypos"		"160"
		"wide"		"176"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
	}
	"listpanel_maplist"
	{
		"ControlName"		"SectionedListPanel"
		"fieldName"		"listpanel_maplist"
		"xpos"		"35"
		"ypos"		"190"
		"wide"		"315"
		"tall"		"170"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
	}
	"StartingMapButton"
	{
		"ControlName"		"Button"
		"fieldName"		"StartingMapButton"
		"xpos"		"10"
		"ypos"		"400"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"Set Starting Map"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"setstartmap"
		"Default"		"0"
		"button_activation_type" "0"
	}
	"BackgroundMapButton"
	{
		"ControlName"		"Button"
		"fieldName"		"BackgroundMapButton"
		"xpos"		"150"
		"ypos"		"400"
		"wide"		"192"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"Set Background Map (Optional)"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"command"		"setbgmap"
		"Default"		"0"
		"button_activation_type" "0"
	}
}