"resource/ui/hl2r_optionssubgame.res"
{
////////////////////////
	// Page Header
////////////////////////
	"HeaderLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HLable"
		"xpos"		"20"
		"ypos"		"15"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_header_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Page Dividers
////////////////////////
	"DividerLeft"
	{
		"ControlName"		"Divider"
		"fieldName"		"DividerLeft"
		"xpos"		"20"
		"ypos"		"70"
		"wide"		"3"
		"tall"		"500"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"2"
	}
	"DividerRight"
	{
		"ControlName"		"Divider"
		"fieldName"		"DividerRight"
		"xpos"		"340"
		"ypos"		"70"
		"wide"		"3"
		"tall"		"500"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"2"
	}
	"DividerTop"
	{
		"ControlName"		"Divider"
		"fieldName"		"DividerTop"
		"xpos"		"20"
		"ypos"		"70"
		"wide"		"320"
		"tall"		"3"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"2"
	}
	"DividerBottom"
	{
		"ControlName"		"Divider"
		"fieldName"		"DividerBottom"
		"xpos"		"20"
		"ypos"		"567"
		"wide"		"320"
		"tall"		"3"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"2"
	}
////////////////////////
	// Toggle Button
////////////////////////
	"toggleAllButton"
	{
		"ControlName"		"Button"
		"fieldName"		"TAButton"
		"xpos"		"310"
		"ypos"		"640"
		"wide"		"72"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Toggle All"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"command"		"toggleall"
		"Default"		"0"
	}
////////////////////////	
	// Shorter Sprint
////////////////////////
	"ShorterSprintButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"SSButton"
		"xpos"		"30"
		"ypos"		"80"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_SS_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"ShorterSprintLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"SSLabel"
		"xpos"		"60"
		"ypos"		"90"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_SS_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Explosive Headcrabs
////////////////////////
	"ExplosiveCrabsButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ECButton"
		"xpos"		"30"
		"ypos"		"160"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_EC_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"ExplosiveCrabsLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ECLabel"
		"xpos"		"60"
		"ypos"		"180"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_EC_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Fear Movement
////////////////////////
	"FearMovementButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"FMButton"
		"xpos"		"30"
		"ypos"		"240"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_FM_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"FearMovementLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"FMLabel"
		"xpos"		"60"
		"ypos"		"250"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_FM_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Less Ammo
////////////////////////
	"LessAmmoButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"LAButton"
		"xpos"		"30"
		"ypos"		"320"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_LA_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"LessAmmoLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"LALabel"
		"xpos"		"60"
		"ypos"		"340"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_LA_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Enemy Promotion
////////////////////////
	"EnemyPromotionButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"EPButton"
		"xpos"		"30"
		"ypos"		"400"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_EP_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"EnemyPromotionLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"EPLabel"
		"xpos"		"60"
		"ypos"		"420"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_EP_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Random Weapons
////////////////////////
	"RandomWeaponsButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RWButton"
		"xpos"		"30"
		"ypos"		"480"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_RW_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"RandomWeaponsLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"RWLabel"
		"xpos"		"60"
		"ypos"		"500"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_RW_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
}
