"resource/ui/hl2r_gameoptionssubgame.res"
{
////////////////////////
	// Page Header
////////////////////////
	"HeaderLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"HLable"
		"xpos"		"30"
		"ypos"		"0"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_header_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Toggle Button
////////////////////////
	"toggleAllButton"
	{
		"ControlName"		"Button"
		"fieldName"		"TAButton"
		"xpos"		"310"
		"ypos"		"640"
		"wide"		"72"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Toggle All"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"command"		"toggleall"
		"Default"		"0"
	}
////////////////////////	
	// Manual pickup
////////////////////////
	"ManualPickupButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"MPButton"
		"xpos"		"30"
		"ypos"		"50"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_MP_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"ManualPickupLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"MPLabel"
		"xpos"		"60"
		"ypos"		"70"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_MP_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Explosive Headcrabs
////////////////////////
	"ExplosiveCrabsButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ECButton"
		"xpos"		"30"
		"ypos"		"130"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_EC_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"ExplosiveCrabsLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ECLabel"
		"xpos"		"60"
		"ypos"		"150"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_EC_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Fear Movement
////////////////////////
	"FearMovementButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"FMButton"
		"xpos"		"30"
		"ypos"		"210"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_FM_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"FearMovementLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"FMLabel"
		"xpos"		"60"
		"ypos"		"220"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_FM_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
////////////////////////
	// Less Ammo
////////////////////////
	"LessAmmoButton"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"LAButton"
		"xpos"		"30"
		"ypos"		"290"
		"wide"		"200"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_LA_title"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"auto_wide_tocontents"		"0"
		"use_proportional_insets"		"0"
		"Default"		"0"
	}
	"LessAmmoLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"LALabel"
		"xpos"		"60"
		"ypos"		"310"
		"wide"		"512"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#hl2r_gameoptions_LA_text"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
}
